//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTransferCoreImpl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentTransferCoreImpl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _轉入_mask_add_64 {
            get {
                object obj = ResourceManager.GetObject("_轉入_mask_add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _轉入轉出確認layers_ok_64 {
            get {
                object obj = ResourceManager.GetObject("_轉入轉出確認layers_ok_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _轉出_image_size_up_64 {
            get {
                object obj = ResourceManager.GetObject("_轉出_image_size_up_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SchoolList&gt;
        ///  &lt;School Name=&quot;私立育才國小&quot; Code=&quot;011601&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立聖心國小&quot; Code=&quot;011602&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立及人國小&quot; Code=&quot;011603&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立竹林國小&quot; Code=&quot;011604&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立信賢種籽親子實小&quot; Code=&quot;011606&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立裕德國小&quot; Code=&quot;011607&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立板橋國小&quot; Code=&quot;014601&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立國光國小&quot; Code=&quot;014602&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eh {
            get {
                return ResourceManager.GetString("eh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Fields&gt;
        ///    &lt;!--這個對照表是用於匯出 Excel 時用的--&gt;
        ///    &lt;Field Pattern=&quot;EnglishName&quot; Chinese=&quot;英文姓名&quot;/&gt;
        ///    &lt;Field Pattern=&quot;BirthPlace&quot; Chinese=&quot;出生地&quot;/&gt;
        ///    &lt;Field Pattern=&quot;PermanentAddress/AddressList/Address[1]&quot; Chinese=&quot;戶籍地址&quot; DataParser=&quot;Address&quot;/&gt;
        ///    &lt;Field Pattern=&quot;MailingAddress/AddressList/Address[1]&quot; Chinese=&quot;聯絡地址&quot; DataParser=&quot;Address&quot;/&gt;
        ///    &lt;Field Pattern=&quot;OtherAddress/AddressList/Address[1]&quot; Chinese=&quot;其他地址1&quot; DataParser=&quot;Address&quot;/&gt;
        ///    &lt;Field Pattern=&quot;OtherAddress/AddressList/Address[2]&quot; Chinese=&quot;其他地址2&quot; D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportNameMap {
            get {
                return ResourceManager.GetString("ExportNameMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SchoolList&gt;
        ///  &lt;School Name=&quot;私立時雨國中&quot; Code=&quot;011501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立板橋國中&quot; Code=&quot;014501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立重慶國中&quot; Code=&quot;014503&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立江翠國中&quot; Code=&quot;014504&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立中山國中&quot; Code=&quot;014505&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新埔國中&quot; Code=&quot;014506&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新莊國中&quot; Code=&quot;014507&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新泰國中&quot; Code=&quot;014508&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jh {
            get {
                return ResourceManager.GetString("jh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OptionList&gt;
        ///    &lt;Options Name=&quot;學生身份註記&quot;&gt;
        ///        &lt;Item&gt;一般學生&lt;/Item&gt;
        ///        &lt;Item&gt;本人身障&lt;/Item&gt;
        ///        &lt;Item&gt;家長身障&lt;/Item&gt;
        ///        &lt;Item&gt;低收入戶&lt;/Item&gt;
        ///        &lt;Item&gt;大陸來台依親者&lt;/Item&gt;
        ///        &lt;Item&gt;功勳子女&lt;/Item&gt;
        ///        &lt;Item&gt;海外僑生&lt;/Item&gt;
        ///        &lt;Item&gt;港澳生&lt;/Item&gt;
        ///        &lt;Item&gt;邊疆生&lt;/Item&gt;
        ///        &lt;Item&gt;原住民&lt;/Item&gt;
        ///        &lt;Item&gt;外籍生&lt;/Item&gt;
        ///        &lt;Item&gt;資優生&lt;/Item&gt;
        ///        &lt;Item&gt;派外人員子女&lt;/Item&gt;
        ///        &lt;Item&gt;體育績優&lt;/Item&gt;
        ///        &lt;Item&gt;顏面傷殘&lt;/Item&gt;
        ///        &lt;Item&gt;教職員子女&lt;/Item&gt;
        ///        &lt;Item&gt;公教遺族-因公&lt;/Item&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Fields&gt;
        ///    &lt;!--這個對照表是用於轉出學生基本資料時用的--&gt;
        ///    &lt;Field PhysicalName=&quot;english_name&quot; EnglishName=&quot;EnglishName&quot; IsXmlContent=&quot;false&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;birth_place&quot; EnglishName=&quot;BirthPlace&quot; IsXmlContent=&quot;false&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;mailing_address&quot; EnglishName=&quot;MailingAddress&quot; IsXmlContent=&quot;true&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;other_addresses&quot; EnglishName=&quot;OtherAddress&quot; IsXmlContent=&quot;true&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;permanent_address&quot; EnglishName=&quot;PermanentAddress&quot; IsXmlContent=&quot;true&quot;/&gt;
        ///    &lt;Field [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StudentFields {
            get {
                return ResourceManager.GetString("StudentFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 綜合資料轉移單 {
            get {
                object obj = ResourceManager.GetObject("綜合資料轉移單", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
